[project]
name = "base64-flashbot-suite"
authors = ["Base64 Flashbot Team"]
description = "A cutting-edge decentralized base64 encoding and transaction optimization platform"
telemetry = false
requirements = []

[contracts.base64-core]
path = "contracts/base64-core.clar"
depends_on = []

[contracts.encoding-metrics]
path = "contracts/encoding-metrics.clar"
depends_on = []

[contracts.crypto-utils]
path = "contracts/crypto-utils.clar"
depends_on = []

[contracts.tx-flashbot]
path = "contracts/tx-flashbot.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
